logging:
  level:
    jdbc.sqlonly: info
    jdbc.resultsottable: info
    jdbc.resultot: info
    jdbc.audit: error
    jdbc.sqltiming: info
    org.hibernate.type: error

server:
  port: 8080

spring:
  profiles.active: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate
    generate-ddl: false
  liquibase:
    drop-first: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml